---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: searxng-mcp
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: searxng-mcp
  dependsOn:
    - name: litellm-operator
      namespace: ai
    - name: searxng
      namespace: selfhosted
  interval: 1h
  path: "./kubernetes/apps/ai/searxng-mcp/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: ai
  timeout: 5m
