apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:meF5VWx7+7oau/Vy,iv:NG4xQZoS4bvEnnUzf5ec5gQwCrHoPXNQQDOCoEPN8lQ=,tag:fhPFo8kHliy5CCvALPgiPQ==,type:str]
    TIMEZONE: ENC[AES256_GCM,data:G96/8eLmXuRnlUAbMQ==,iv:VH8GzLAaoYv0lNo3NNzgNI50gnPYNAIoNtkvTmsTDB8=,tag:ru1s7wu1CB/Vo3m+nknQaA==,type:str]
sops:
    age:
        - recipient: age13jyzwq3g290ktqzmv6t0eytrww4zs76u3pg2e7cu7yeznjpk2fsqn4ngm2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMWm15MnhsRWVvWk5kMEtj
            eDlKaDB0Z0tSNGxpdXZaU3NWTFM3TjFUOVVnClpiOG5OVU0vVUVXQXlQdHB4TTNu
            N2dKTTZwVzFjLzlGUnE4bk00K1lzaFUKLS0tIE56dktiYmpwa043a0NBR2Q3am5L
            MC9OU0NscVByMEd2c2VZOVBvWGxodjgKwVovOj9zeyzp6iqIHmNiEzvKn5WpqxYk
            NrtzKU8QovY9ZNNPEKbKQoCdY+08PZw5V6DEphD+M56P1Jq6IEjILw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-17T08:03:28Z"
    mac: ENC[AES256_GCM,data:kYGxnFbvVzwN8lja+JCPjlA82E4ENeHzjeTEn2NhVysrcx/2U2/+6kzlK5poVdGCd9BaMrHu5vpcrw/FcTifs3nvDeQgBSwsL8Z6HNLr7vUdpsB8C14p7OPJoN7YYqIGdLlJ4FEj8UCI7SLbtgOUG9EVELgW/FGifaih49qs8MU=,iv:PrdF16vNKxCprdcKz6wFKupg4SZ9XGm29PuezJHD3RA=,tag:y7ytJJL3c3uPzImb7OCcQA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
