---
all:
  children:
    semaphore:
      hosts:
        vpn-stream-escritorio.local.jaimenet.com:
          ansible_user: root
        vpnstreamcasal.local.jaimenet.com:
          ansible_user: root
        vpntor.jaimenet.com:
          ansible_user: root
        kasm.local.jaimenet.com:
          ansible_user: root
        ai.local.jaimenet.com:
          ansible_user: root
        nexterm.local.jaimenet.com:
          ansible_user: root
        plex.local.jaimenet.com:
          ansible_user: root
        zig2mqgaragem.home.jaimenet.com:
          ansible_user: root
        zig2mqcasa.jaimenet.com:
          ansible_user: root
        mqtt.jaimenet.com:
          ansible_user: root
