---
# yaml-language-server: $schema=https://schemas.recyclarr.dev/v8/config-schema.json
sonarr:
  sonarr:
    base_url: http://sonarr.downloads.svc.cluster.local
    api_key: !env_var SONARR_API_KEY
    delete_old_custom_formats: true
    include:
      - template: web-1080p

radarr:
  radarr:
    base_url: http://radarr.downloads.svc.cluster.local:7878
    api_key: !env_var RADARR_API_KEY
    delete_old_custom_formats: true
    include:
      - template: sqp-1-2160p
