---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ha-status
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: ha-status-secret
    creationPolicy: Owner
    template:
      data:
        MQTT_USERNAME: "{{ .mqtt_username }}"
        MQTT_PASSWORD: "{{ .mqtt_password }}"
  dataFrom:
    # 1Password item with fields mqtt_username / mqtt_password.
    - extract:
        key: mqtt
